In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('artifacts/kyphosis.csv')

In [3]:
data.head()

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [4]:
data.shape

(81, 4)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64
 2   Number    81 non-null     int64
 3   Start     81 non-null     int64
dtypes: int64(3), object(1)
memory usage: 2.7+ KB

In [6]:
x = data.drop('Kyphosis', axis=1)

In [7]:
x.head()

   Age  Number  Start
0   71       3      5
1  158       3     14
2  128       4      5
3    2       5      1
4    1       4     15

In [8]:
y = data['Kyphosis']

In [9]:
y.head()

0     absent
1     absent
2    present
3     absent
4     absent
Name: Kyphosis, dtype: object

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [11]:
x_train.shape

(56, 3)

In [12]:
y_train.shape

(56,)

### Random Forest

In [51]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 50)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=50)

In [52]:
pred = model.predict(x_test)
pred

array(['absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'absent', 'absent',
       'absent', 'absent', 'absent', 'absent', 'present', 'absent',
       'absent', 'absent', 'present', 'present', 'absent', 'absent',
       'absent'], dtype=object)

In [53]:
y_test

49     absent
31     absent
69     absent
7      absent
8      absent
23     absent
40    present
57    present
63     absent
9     present
4      absent
48    present
38     absent
51     absent
66     absent
3      absent
21    present
61    present
59     absent
55     absent
12     absent
2     present
0      absent
74     absent
45    present
Name: Kyphosis, dtype: object

In [54]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.72

In [55]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[16,  1],
       [ 6,  2]])